# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maryknoll', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollmentt_Details',
            new_name='Enrollment_Details',
        ),
    ]
